export const groups = [
  {
    id: 1,
    name: "City Center Badminton Club",
    description: "120 Members | Weekly Matches",
    category: "sports",
    image: "../img/balmiton.jpg",
  },
  {
    id: 2,
    name: "Downtown Soccer League",
    description: "200 Members | Daily Practices",
    category: "sports",
    image: "../img/tennis.jpg",
  },
  {
    id: 3,
    name: "Local Tennis Champs",
    description: "75 Members | Monthly Tournaments",
    category: "fitness",
    image: "../img/soccer.jpg",
  },
  {
    id: 4,
    name: "Community Cricket Club",
    description: "150 Members | Weekend Games",
    category: "sports",
    image: "../img/cricket.jpg",
  },
  {
    id: 5,
    name: "Fitness Freaks Jogging Club",
    description: "60 Members | Morning Sessions",
    category: "fitness",
    image: "../img/fitness.avif",
  },
  {
    id: 6,
    name: "Chess Enthusiasts",
    description: "50 Members | Weekly Challenges",
    category: "games",
    image: "../img/chess.jpg",
  },
  {
    id: 7,
    name: "Mountain Biking Group",
    description: "40 Members | Weekly Adventures",
    category: "fitness",
    image: "../img/mbike.webp",
  },
  {
    id: 8,
    name: "Local Tennis Champs",
    description: "75 Members | Monthly Tournaments",
    category: "sports",
    image: "../img/tabletennis.jpg",
  },
  {
    id: 9,
    name: "Urban Yoga Club",
    description: "100 Members | Daily Sessions",
    category: "fitness",
    image: "../img/yoga.jpg",
  },
  {
    id: 10,
    name: "Table Tennis Pro Club",
    description: "50 Members | Weekend Matches",
    category: "games",
    image: "../img/tennis.jpg",
  },
];
