export const activities = [
  {
    id: 1,
    name: "Counter-Strike 2 Tournament",
    description: "Join our weekly CS2 competitions and test your skills.",
    category: "online",
    image: "../img/cs2.jpg",
  },
  {
    id: 2,
    name: "Dota 2 Battle Arena",
    description: "Compete with the best in our Dota 2 battle arena!",
    category: "online",
    image: "../img/dota2.jpg",
  },
  {
    id: 3,
    name: "Chess Blitz Matches",
    description: "Weekly chess blitz games for all skill levels.",
    category: "online",
    image: "../img/chess_online.jpg",
  },
  {
    id: 4,
    name: "Basketball League",
    description: "Join the local basketball league for regular matches.",
    category: "offline",
    image: "../img/basketball.jpg",
  },
  {
    id: 5,
    name: "Football Community Cup",
    description: "Play football in our community tournaments.",
    category: "offline",
    image: "../img/football.jpg",
  },
  {
    id: 6,
    name: "Yoga in the Park",
    description: "Relax and rejuvenate with our outdoor yoga sessions.",
    category: "offline",
    image: "../img/yoga_park.jpg",
  },
  {
    id: 7,
    name: "Table Tennis Duel",
    description: "Face off in exciting table tennis matches.",
    category: "offline",
    image: "../img/tabletennis_offline.jpg",
  },
  {
    id: 8,
    name: "Call of Duty: Warzone",
    description: "Dominate the battlegrounds in Warzone tournaments.",
    category: "online",
    image: "../img/warzone.jpg",
  },
  {
    id: 9,
    name: "Cycling Adventure",
    description: "Join our weekend cycling adventures through scenic routes.",
    category: "offline",
    image: "../img/cycling.jpg",
  },
  {
    id: 10,
    name: "FIFA Online Showdown",
    description: "Compete in FIFA tournaments from the comfort of your home.",
    category: "online",
    image: "../img/fifa_online.jpg",
  },
];
