export const groups = [
    {
        id: 1,
        name: "City Center Badminton Club",
        description: "120 Members | Weekly Matches",
        category: "sports",
        image: "https://via.placeholder.com/250x150.png?text=Badminton+Club",
    },
    {
        id: 2,
        name: "Downtown Soccer League",
        description: "200 Members | Daily Practices",
        category: "sports",
        image: "https://via.placeholder.com/250x150.png?text=Soccer+League",
    },
    {
        id: 3,
        name: "Local Tennis Champs",
        description: "75 Members | Monthly Tournaments",
        category: "fitness",
        image: "https://via.placeholder.com/250x150.png?text=Tennis+Champs",
    },
    {
        id: 4,
        name: "Community Cricket Club",
        description: "150 Members | Weekend Games",
        category: "sports",
        image: "https://via.placeholder.com/250x150.png?text=Cricket+Club",
    },
    {
        id: 5,
        name: "Fitness Freaks Jogging Club",
        description: "60 Members | Morning Sessions",
        category: "fitness",
        image: "https://via.placeholder.com/250x150.png?text=Jogging+Club",
    },
    {
        id: 6,
        name: "Chess Enthusiasts",
        description: "50 Members | Weekly Challenges",
        category: "games",
        image: "https://via.placeholder.com/250x150.png?text=Chess+Club",
    },
    {
        id: 7,
        name: "Mountain Biking Group",
        description: "40 Members | Weekly Adventures",
        category: "fitness",
        image: "https://via.placeholder.com/250x150.png?text=Biking+Group",
    },
    {
        id: 8,
        name: "Local Tennis Champs",
        description: "75 Members | Monthly Tournaments",
        category: "sports",
        image: "https://via.placeholder.com/250x150.png?text=Tennis+Champs",
    },
    {
        id: 9,
        name: "Urban Yoga Club",
        description: "100 Members | Daily Sessions",
        category: "fitness",
        image: "https://via.placeholder.com/250x150.png?text=Yoga+Club",
    },
    {
        id: 10,
        name: "Table Tennis Pro Club",
        description: "50 Members | Weekend Matches",
        category: "games",
        image: "https://via.placeholder.com/250x150.png?text=Table+Tennis",
    },

];
